// BPHS Programme Part 44 — Chapter 64: the antardasa effects of the Kalachakra dasha.
//
// At **10,229 lines** this is the largest single chapter in BPHS — larger than chapter 61 —
// and **93.6% of it is table markup**: 9,577 lines of tables against 14 numbered verses. The
// tables look like a 12 amsa × 12 dasha rasi × 12 antardasa structure, and they are generated
// by a **twelve-element vector and one formula**, both of which the engine already had.
//
// So the extraction is small. The findings are not:
//
//   1. **`KALACHAKRA_RASI_YEARS` is independently confirmed**, all twelve values, from 36
//      observations in a chapter that had no part in producing it.
//   2. **A transcription fault in the chapter's own summary table**, caught by four
//      independent checks that agree against it.
//   3. **64.56-58 states a FRIENDSHIP rule** — the relation between the antar lord and the
//      dasha lord outranks the antar lord's benefic nature. The fourteenth source-stated
//      arbitration instruction, and encodable.
//   4. **64.56-58 also says the chapter's material is stated for SAVYA**, which is textual
//      support for the first of the two candidate readings Part 36 left open.

import type { SignIndex, Graha } from '../../types.js';
import { KALACHAKRA_RASI_YEARS } from '../kalachakra.js';
import { lordOfSign } from '../../rules/predicate.js';
import { naturalRelationOf } from './ch03.js';

// ─────────────────────────────────────────────────────────────────────────────
// The reconciliation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Chapter 64 confirms `KALACHAKRA_RASI_YEARS` from a completely independent direction.
 *
 * The shipped vector came from chapter 46's Table 43 (Part 36). This chapter never states it
 * as a table at all — it is embedded in **41 section headings** of the form *"Antardasa of
 * Rāśhis in the Dasha of Aries (7 Years) in Aries Amsa"*, scattered across 10,229 lines and
 * grouped by amsa rather than by rasi.
 *
 * Extracting those headings gives **36 usable (amsa, rasi, years) observations**. Every rasi
 * that appears more than once appears with the **same** year count each time, and the twelve
 * values recovered are exactly the shipped vector:
 *
 * ```
 * Aries 7 · Taurus 16 · Gemini 9 · Cancer 21 · Leo 5 · Virgo 9
 * Libra 16 · Scorpio 7 · Sagittarius 10 · Capricorn 4 · Aquarius 4 · Pisces 10
 * ```
 *
 * **Zero conflicts across 36 observations, and nothing changed.** This is Part 34's shape: a
 * second, independent statement of data the engine already ships, used as a check on it.
 */
export const RASI_YEARS_CONFIRMED_INDEPENDENTLY =
  'Chapter 64 confirms `KALACHAKRA_RASI_YEARS` from an independent direction. The shipped '
  + 'vector came from chapter 46’s Table 43 (Part 36); this chapter never states it as a table '
  + 'at all, embedding it instead in 41 section headings of the form "Dasha of Aries (7 Years) '
  + 'in Aries Amsa", scattered over 10,229 lines and grouped by AMSA rather than by rasi. '
  + 'Those yield 36 usable (amsa, rasi, years) observations; every rasi appearing more than '
  + 'once appears with the SAME count each time, and the twelve recovered values are exactly '
  + 'the shipped vector. ZERO conflicts, NOTHING CHANGED.';

/**
 * **The structural finding: the Kalachakra dasha years are a per-RASI constant.**
 *
 * The chapter's layout invites the opposite conclusion. It presents a separate block of tables
 * for each of the twelve amsas, so the natural reading is that a rasi's dasha length depends
 * on the amsa it is read in — a 12 × 12 table of 144 values.
 *
 * It does not. Across the 36 observations, Aries is 7 years in the Aries, Gemini, Virgo **and**
 * Aquarius amsas; Sagittarius is 10 in four different amsas; Capricorn and Aquarius are 4 in
 * four each. Not one rasi takes two values.
 *
 * So the whole chapter — 9,577 lines of tables — is generated by **twelve numbers and one
 * formula**: `kalachakraAntardasaYears(dashaYears, antarRasiYears)` from Part 39. What varies
 * between amsas is not the years but the **sequence** in which the rasis run, which Part 36
 * already encoded as the savya and apasavya wheels.
 */
export const RASI_YEARS_ARE_A_PER_RASI_CONSTANT =
  'The Kalachakra dasha years are a per-RASI constant, not a per-(amsa, rasi) table — despite '
  + 'chapter 64 presenting a separate block of tables for each of the twelve amsas, which '
  + 'invites the opposite reading. Across 36 observations Aries is 7 years in the Aries, '
  + 'Gemini, Virgo AND Aquarius amsas, Sagittarius is 10 in four amsas, Capricorn and Aquarius '
  + '4 in four each; not one rasi takes two values. So 9,577 lines of tables are generated by '
  + 'TWELVE NUMBERS and one formula (Part 39’s `kalachakraAntardasaYears`). What varies between '
  + 'amsas is the SEQUENCE, which Part 36 already encoded as the savya/apasavya wheels.';

/**
 * ⚠️ A transcription fault in the chapter's one summary table, and the four checks that
 * caught it.
 *
 * *"Table showing Dasha years in Aries Amsa"* lists nine rasis with the years
 * `7, 16, 9, 21, 5, 9, 16, 17, 10` and a stated **Total 100**. The eighth entry is Scorpio,
 * printed as **17**. Four independent things say it should be **7**:
 *
 *   1. The row sums to 110 as printed and to **exactly 100** with 7 — its own stated total.
 *   2. Four section headings elsewhere in the chapter give Scorpio's dasha as **7 Years**.
 *   3. The shipped `KALACHAKRA_RASI_YEARS`, sourced from chapter 46, has Scorpio at 7.
 *   4. BPHS 46.89 gives the Aries amsa a poornayu of **100**, which the corrected row meets.
 *
 * Recorded, not corrected — the shipped value was already 7, so there is nothing to change.
 * What is worth keeping is the *shape* of the evidence: a single digit is wrong, and four
 * unrelated checks converge on the same replacement.
 */
export const ARIES_AMSA_TABLE_HAS_ONE_FAULT =
  'Chapter 64’s one summary table ("Dasha years in Aries Amsa") prints 7, 16, 9, 21, 5, 9, 16, '
  + '17, 10 with a stated Total 100. The eighth entry is SCORPIO, printed as 17; it should be '
  + '7, and four independent checks converge on that: the row sums to 110 as printed and '
  + 'exactly 100 with 7 (its own stated total); four section headings elsewhere give Scorpio’s '
  + 'dasha as 7 Years; the shipped vector from chapter 46 has 7; and 46.89 gives the Aries '
  + 'amsa a poornayu of 100, which the corrected row meets. Nothing to change — the shipped '
  + 'value was already 7. Recorded for the SHAPE of the evidence.';

// ─────────────────────────────────────────────────────────────────────────────
// 64.56-58 — the friendship rule
// ─────────────────────────────────────────────────────────────────────────────

/**
 * BPHS 64.56-58, the chapter's closing instruction and the only part of its prose that
 * generalises:
 *
 *   *"The peculiarity in this respect is that inauspicious results have been ascribed to
 *    malefics. But if during the Antardasa the planet concerned be **a friend of the lord of
 *    the Dasha**, the results of the Antardasa will be favourable. If the planet concerned be
 *    a benefic but **an enemy of the lord of the Dasha**, his Antardasa effects will not prove
 *    favourable."*
 *
 * **The fourteenth source-stated arbitration instruction**, and a genuinely new axis: the
 * previous thirteen weigh a planet's own condition (dignity, house, varga) against its nature.
 * This weighs the **relation between two planets** against one of their natures.
 *
 * ⚠️ **This does not reopen the enmity axis Part 41 closed, and the distinction matters.**
 * Part 40 proposed that BPHS 54.30-32 (Mars's dasha, Saturn's antardasa reading adversely for
 * favourable positions) was explained by the two lords' enmity. Part 41 refuted that for the
 * *Vimshottari* block, because 57.55-57 reads the same pair favourably in the other order and
 * an enmity rule would be symmetric. That refutation stands untouched.
 *
 * What this adds is that BPHS **does** state a friendship rule — explicitly, and for the
 * **Kalachakra** dasha, whose parties are rasis rather than planets. A rule the source states
 * for one system is not evidence for an unstated rule in another; Part 41 tested that and it
 * failed. So: encoded here, for Kalachakra, and not carried across.
 */
export const KALACHAKRA_FRIENDSHIP_RULE =
  'BPHS 64.56-58: "inauspicious results have been ascribed to malefics. But if during the '
  + 'Antardasa the planet concerned be A FRIEND OF THE LORD OF THE DASHA, the results will be '
  + 'favourable. If the planet be a benefic but AN ENEMY of the lord of the Dasha, his '
  + 'Antardasa effects will not prove favourable." The FOURTEENTH source-stated arbitration '
  + 'instruction and a NEW AXIS: the previous thirteen weigh a planet’s own condition against '
  + 'its nature, this weighs the RELATION BETWEEN TWO PLANETS against one of their natures. '
  + 'It does NOT reopen the enmity axis Part 41 closed — that was about an UNSTATED rule in '
  + 'the Vimshottari block, tested and refuted. This one the source states, for Kalachakra, '
  + 'whose parties are rasis. Encoded here and deliberately NOT carried across.';

export interface KalachakraAntarVerdict {
  /** Lords of the two rasis, which is what the rule actually compares. */
  dashaLord: Graha;
  antarLord: Graha;
  relation: 'friend' | 'enemy' | 'neutral' | 'same' | 'unknown';
  valence: number;
  summary: string;
}

/**
 * BPHS 64.56-58 as a reading over a (dasha rasi, antardasa rasi) pair.
 *
 * The rule is stated about *planets* but applies to a rasi dasha, so the comparison is between
 * the **lords** of the two rasis — which is what "the lord of the Dasha" means when the dasha
 * belongs to a sign.
 *
 * ⚠️ The relation is read **from the dasha lord's table**, because the verse says the antar
 * planet is *"a friend of the lord of the Dasha"*. That direction matters: the natural
 * relations are asymmetric — Mars counts Mercury an enemy while Mercury counts Mars neutral —
 * so the two readings disagree for real pairs, and the first draft had it backwards.
 *
 * Silence rather than a guess in two cases the verse does not cover: when both rasis share a
 * lord (there is no relation between a planet and itself), and when either lord is a node, for
 * which `naturalRelationOf` deliberately returns null — see `NODE_RELATIONS`.
 */
export function kalachakraAntarVerdict(
  dashaRasi: SignIndex, antarRasi: SignIndex,
): KalachakraAntarVerdict {
  const dashaLord = lordOfSign(dashaRasi);
  const antarLord = lordOfSign(antarRasi);
  if (dashaLord === antarLord) {
    return {
      dashaLord, antarLord, relation: 'same', valence: 0,
      summary: 'One planet rules both signs, so the verse’s comparison does not arise.',
    };
  }
  // "a friend OF THE LORD OF THE DASHA" — read from the DASHA lord's table. The natural
  // relations are not symmetric (Mars counts Mercury an enemy; Mercury counts Mars neutral),
  // so the argument order is a correctness question, not a stylistic one.
  const rel = naturalRelationOf(dashaLord, antarLord);
  if (rel == null) {
    return {
      dashaLord, antarLord, relation: 'unknown', valence: 0,
      summary: 'No natural relation is defined for this pair, so the verse gives no reading.',
    };
  }
  if (rel === 'friend') {
    return {
      dashaLord, antarLord, relation: 'friend', valence: 0.6,
      summary: 'The sub-period’s ruler is at ease with the period’s — it runs with the grain.',
    };
  }
  if (rel === 'enemy') {
    return {
      dashaLord, antarLord, relation: 'enemy', valence: -0.5,
      summary: 'The sub-period’s ruler is at odds with the period’s — it runs against the grain.',
    };
  }
  return {
    dashaLord, antarLord, relation: 'neutral', valence: 0,
    summary: 'Neither ruler favours nor opposes the other; the period takes its colour elsewhere.',
  };
}

/**
 * ⚠️ **Textual support for the first of Part 36's two candidate readings.**
 *
 * Part 36 found BPHS 46.89's poornayu table matching the shipped paramayush for **all 60 savya
 * padas and none of the 48 apasavya ones**, and left two candidate explanations open:
 * *(1) 46.89 is stated for the savya case only, or (2) its "Amsa" is not 46.87-88's navamsa.*
 *
 * 64.56-58 opens with: *"The effects of Antardasa in the Kalachakra Dasha which have been
 * described above are **based on Savya chakra**. The effects of Antardasa in the Dasha of
 * rāśhis in Apasavya chakra have to be assessed [separately]."*
 *
 * So the corpus **does** state Kalachakra material for savya and hand apasavya off to a
 * different treatment — which is exactly the pattern candidate (1) predicts, in a second
 * chapter, about a second body of material.
 *
 * **This is support, not a resolution.** It says the savya/apasavya split is a real editorial
 * habit of the Kalachakra chapters; it does not say 46.89 in particular is savya-only, and it
 * supplies no apasavya poornayu to test against. The thread stays open — but candidate (1) is
 * no longer symmetric with candidate (2), and a later part should weigh them accordingly.
 */
export const SAVYA_ONLY_HABIT_SUPPORTS_CANDIDATE_ONE =
  'BPHS 64.56-58 opens: "The effects of Antardasa in the Kalachakra Dasha which have been '
  + 'described above are BASED ON SAVYA CHAKRA. The effects... in Apasavya chakra have to be '
  + 'assessed [separately]." Part 36 left two candidates for why 46.89’s poornayu matches all '
  + '60 savya padas and none of the 48 apasavya: (1) 46.89 is stated for savya only, or (2) '
  + 'its "Amsa" is not the navamsa. This is the pattern candidate (1) predicts, in a SECOND '
  + 'chapter about a SECOND body of material — the savya-only habit is real. SUPPORT, NOT A '
  + 'RESOLUTION: it does not say 46.89 in particular is savya-only and supplies no apasavya '
  + 'poornayu to test. The thread stays open, but the two candidates are no longer symmetric.';

// ─────────────────────────────────────────────────────────────────────────────
// The per-amsa effect prose — refused
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Chapter 64's twelve blocks of per-amsa effect prose (verses 2-55) are **not encoded**, on
 * the ground Part 38 already established for the same material one level up.
 *
 * Part 38 refused **chapter 49's 144-cell Kalachakra effects table** because roughly two cells
 * in nine survived the medical and hazard filters. This chapter is the same subject one level
 * down and reads the same way — verse 2, the one fully-stated cell, gives *"wounds and fever
 * in the Antardasa of Mars… danger from enemy in the Antardasa of the Sun"*, and verse 3-5
 * gives *"quarrels, diseases… in the Antardasa of Saturn"*.
 *
 * It is also **mostly not stated**: nine of the twelve blocks are a heading followed by a
 * table (*"the effects in the various Antardasa of the rāśhis concerned will be as follows-"*),
 * so the prose that would be refused largely does not exist in transcribable form.
 *
 * What replaces it is better than what it refuses: **64.56-58's friendship rule covers the
 * same question structurally**, for every (dasha rasi, antar rasi) pair, with no medical
 * content — exactly as chapter 50's nine clauses replaced chapter 49's table in Part 38.
 */
export const CH64_EFFECT_PROSE_REFUSED =
  'Chapter 64’s twelve blocks of per-amsa effect prose (verses 2-55) are NOT encoded, on the '
  + 'ground Part 38 established for the same material one level up — it refused chapter 49’s '
  + '144-cell Kalachakra table because ~2 cells in 9 survived the medical and hazard filters. '
  + 'This reads the same: verse 2 gives "wounds and fever in the Antardasa of Mars… danger '
  + 'from enemy in the Antardasa of the Sun"; 3-5 gives "quarrels, diseases". It is also '
  + 'mostly NOT STATED — nine of the twelve blocks are a heading followed by a table. And '
  + 'what replaces it is better: 64.56-58’s friendship rule covers the same question '
  + 'STRUCTURALLY for every (dasha rasi, antar rasi) pair with no medical content — exactly as '
  + 'chapter 50’s clauses replaced chapter 49’s table in Part 38.';

/** The confirmed vector, re-exported under this chapter's name so the check is traceable. */
export const CH64_RASI_YEARS: readonly number[] = KALACHAKRA_RASI_YEARS;

export const CH64_YIELD = {
  chapters: [64],
  note: 'The LARGEST single chapter in BPHS (10,229 lines) and 93.6% table markup — 9,577 '
    + 'lines of tables against 14 verses — generated by TWELVE NUMBERS and one formula the '
    + 'engine already had. Four findings. (1) `KALACHAKRA_RASI_YEARS` is INDEPENDENTLY '
    + 'CONFIRMED: 36 observations recovered from section headings, zero conflicts, all twelve '
    + 'values exact, nothing changed. (2) The years are a per-RASI CONSTANT, not the 12×12 '
    + 'table the layout implies — what varies between amsas is the sequence. (3) 64.56-58 '
    + 'states a FRIENDSHIP RULE — the relation between the antar lord and the dasha lord '
    + 'outranks nature — the 14th source-stated arbitration instruction and a genuinely new '
    + 'axis, now encoded as `kalachakraAntarVerdict`. It does NOT reopen the enmity axis Part '
    + '41 closed, which was about an unstated rule in a different system. (4) The same verse '
    + 'says the material is stated for SAVYA, which supports the first of Part 36’s two '
    + 'candidate readings without resolving the thread. The per-amsa effect prose is refused '
    + 'on Part 38’s chapter-49 ground.',
} as const;
